# Generated by Django 5.0.2 on 2024-05-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_cliente', models.BooleanField(default=False)),
                ('is_mensajero', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('direccion', models.CharField(blank=True, default='NULL', max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, default='NULL', max_length=20)),
                ('identificacion', models.CharField(max_length=20)),
                ('imagenPerfil', models.ImageField(null=True, upload_to='perfil_imagenes/')),
                ('ciudad', models.CharField(max_length=100)),
                ('nombreSucursal', models.CharField(blank=True, max_length=255)),
                ('telefonoSucursal', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('vehiculo', models.CharField(blank=True, choices=[('M', 'Moto'), ('C', 'Carro'), ('F', 'Camion')], max_length=1)),
                ('placaVehiculo', models.CharField(blank=True, max_length=6)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
