# Generated by Django 5.0.2 on 2024-06-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_is_staff_alter_usuario_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ciudad',
            field=models.CharField(blank=True, choices=[('C', 'Santiago de Cali'), ('B', 'Bogota'), ('M', 'Medellin'), ('P', 'Pereira')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(blank=True, default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, default=' ', max_length=20),
        ),
    ]
