# Generated by Django 5.0.2 on 2024-06-08 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_nombres_alter_usuario_ciudad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='address',
            new_name='address_sucursal',
        ),
    ]
