# Generated by Django 5.0.2 on 2024-05-29 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=100)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estados', models.CharField(blank=True, choices=[('S', 'Solicitado.'), ('A', 'Agendado, un mensajero tomo tu pedido.'), ('C', 'Tu envío está en camino.'), ('D', 'Tu envío ha llegado a su destino.'), ('E', 'Tu envío ha sido entregado.')], max_length=1)),
                ('descripcion', models.CharField(max_length=300)),
                ('direccion_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion2', to='solicitudes.direccion')),
                ('direccion_recojer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direccion1', to='solicitudes.direccion')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_cliente', to=settings.AUTH_USER_MODEL)),
                ('id_mensajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_mensajero', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
