# Generated by Django 5.0.2 on 2024-05-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccion',
            name='direccion',
            field=models.CharField(max_length=300),
        ),
    ]
