# Generated by Django 5.0.2 on 2024-05-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_direccion_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='vehiculoSolicitado',
            field=models.CharField(blank=True, choices=[('M', 'Moto'), ('C', 'Carro'), ('F', 'Camion')], max_length=1),
        ),
    ]
