# Generated by Django 5.0.2 on 2024-06-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_servicio_vehiculosolicitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='is_complete',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
