# Generated by Django 5.0.2 on 2024-06-10 03:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_servicio_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
